name: Build MakuTweaker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v6

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1

    - name: Restore NuGet packages
      run: nuget restore MakuTweakerNew.sln

    - name: Build Project
      shell: pwsh
      run: |
        msbuild MakuTweakerNew.sln `
          /p:Configuration=Debug `
          /p:Platform=x64 `
          /p:FileVersion=$env:BuildNumber `
          /p:AssemblyVersion=$env:BuildNumber

    - name: Copy output for artifact
      run: |
        mkdir -Force build_output
        cp -Recurse bin\Debug\net8.0-windows10.0.19041.0\* build_output\

    - name: Upload artifacts
      uses: actions/upload-artifact@v7
      with:
        name: MakuTweaker-Debug
        path: build_output/
